apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-ecs-service-restarter
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aws-ecs-service-restarter
            image: dtrierweiler/aws-ecs-service-restarter
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-ecs
                    key: access-key
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-ecs
                    key: secret-key
              - name: AWS_REGION
                value: eu-central-1
              - name: ECS_CLUSTER
                value: max-e-magnolia-cluster
              - name: ECS_SERVICE
                value: max-e-magnolia-author
          restartPolicy: Never
